//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationController.Hardware {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkstationController.Hardware.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 drop tip at predefined position. 的本地化字符串。
        /// </summary>
        internal static string BF {
            get {
                return ResourceManager.GetString("BF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 drop tip at specified position. 的本地化字符串。
        /// </summary>
        internal static string BT {
            get {
                return ResourceManager.GetString("BT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 get tip at specified position. 的本地化字符串。
        /// </summary>
        internal static string FT {
            get {
                return ResourceManager.GetString("FT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set X-Ramp parameters. 的本地化字符串。
        /// </summary>
        internal static string FX {
            get {
                return ResourceManager.GetString("FX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Y-Ramp parameters. 的本地化字符串。
        /// </summary>
        internal static string FY {
            get {
                return ResourceManager.GetString("FY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Z-Ramp parameters. 的本地化字符串。
        /// </summary>
        internal static string FZ {
            get {
                return ResourceManager.GetString("FZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 set overall machine limitation. 的本地化字符串。
        /// </summary>
        internal static string OM {
            get {
                return ResourceManager.GetString("OM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 move to absolute position. 的本地化字符串。
        /// </summary>
        internal static string PA {
            get {
                return ResourceManager.GetString("PA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 move to fixed position. 的本地化字符串。
        /// </summary>
        internal static string PF {
            get {
                return ResourceManager.GetString("PF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 get current {0} position. 的本地化字符串。
        /// </summary>
        internal static string RG {
            get {
                return ResourceManager.GetString("RG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 set Z parameters for absolute field. 的本地化字符串。
        /// </summary>
        internal static string SA {
            get {
                return ResourceManager.GetString("SA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 set rack position. 的本地化字符串。
        /// </summary>
        internal static string SF {
            get {
                return ResourceManager.GetString("SF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 set liquid search frequency. 的本地化字符串。
        /// </summary>
        internal static string SL {
            get {
                return ResourceManager.GetString("SL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 set absolute field. 的本地化字符串。
        /// </summary>
        internal static string SM {
            get {
                return ResourceManager.GetString("SM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 set position recovery. 的本地化字符串。
        /// </summary>
        internal static string SP {
            get {
                return ResourceManager.GetString("SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 set Z-Parameters for a position. 的本地化字符串。
        /// </summary>
        internal static string SR {
            get {
                return ResourceManager.GetString("SR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 set liquid detection sensitivity. 的本地化字符串。
        /// </summary>
        internal static string SS {
            get {
                return ResourceManager.GetString("SS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set tip type. 的本地化字符串。
        /// </summary>
        internal static string ST {
            get {
                return ResourceManager.GetString("ST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 set position for the Nth waste. 的本地化字符串。
        /// </summary>
        internal static string SW {
            get {
                return ResourceManager.GetString("SW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 set Z-travel for the next X/Y move. 的本地化字符串。
        /// </summary>
        internal static string SZ {
            get {
                return ResourceManager.GetString("SZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 move X to absolute position. 的本地化字符串。
        /// </summary>
        internal static string XA {
            get {
                return ResourceManager.GetString("XA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 move n steps in X  from current position. 的本地化字符串。
        /// </summary>
        internal static string XR {
            get {
                return ResourceManager.GetString("XR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 move Y to absolute position. 的本地化字符串。
        /// </summary>
        internal static string YA {
            get {
                return ResourceManager.GetString("YA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 move n steps in Y from current position. 的本地化字符串。
        /// </summary>
        internal static string YR {
            get {
                return ResourceManager.GetString("YR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 move Z to absolute position. 的本地化字符串。
        /// </summary>
        internal static string ZA {
            get {
                return ResourceManager.GetString("ZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 move n steps in Z from current position. 的本地化字符串。
        /// </summary>
        internal static string ZR {
            get {
                return ResourceManager.GetString("ZR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 detect liquid. 的本地化字符串。
        /// </summary>
        internal static string ZX {
            get {
                return ResourceManager.GetString("ZX", resourceCulture);
            }
        }
    }
}
